title: Sling
description: SLING    is powerful  Programming  Language invented    in  WEB  by  wilmix jemin  j for  Terminal WebService at  year  2016.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
